# Generated by Django 4.2 on 2023-06-07 13:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("estimate", "Estimate"),
                            ("order", "Order"),
                            ("system_Alert", "System Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("is_seen", models.BooleanField(default=False)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="notifications", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
