# Generated by Django 4.2 on 2023-06-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
