# Generated by Django 4.2 on 2024-08-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_notification_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("estimate", "Estimate"),
                    ("order", "Order"),
                    ("system_Alert", "System Alert"),
                    ("system_user_alert", "System User Alert"),
                ],
                max_length=20,
            ),
        ),
    ]
