# Etapa 1: Construcción de la aplicación React
FROM node:20 AS build

# Establece el directorio de trabajo
WORKDIR /app

# Copia package.json y package-lock.json (si existe)
COPY package*.json ./

# Instala dependencias
RUN npm install

# Copia el resto de los archivos del proyecto
COPY . .

# Construye la aplicación React (contenido estático)
RUN npm run build

# Etapa 2: Servir la aplicación usando NGINX
FROM nginx:alpine AS production

# Copia los archivos de compilación desde la fase de construcción
COPY --from=build /app/build /usr/share/nginx/html

# Copia el archivo de configuración de NGINX personalizado
COPY nginx.prod.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto en el que correrá NGINX
EXPOSE 3005

# Comando para iniciar NGINX
CMD ["nginx", "-g", "daemon off;"]
