server {
    listen 3005;

    server_name localhost;

    # Servir los archivos estáticos de React
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri /index.html;
    }

    # Opcional: Manejo de errores
    error_page 404 /index.html;
}
