services:
  backend_app:
    build:
      context: ./backend
    container_name: backend_app
    volumes:
      - ./backend:/app
      - ./backend/nginx/gunicorn.conf.py:/etc/nginx/gunicorn.conf.py
      - ./backend/local_backup:/app/backup
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    networks:
      - dealerportal_network

networks:
  dealerportal_network:
    driver: bridge