services:
  aws_backend_app:
    build:
      context: ./backend
      dockerfile: Dockerfile.aws.backend.prod
    container_name: aws_backend_app
    volumes:
      - ./backend:/app
      - ./backend/nginx/gunicorn.conf.py:/etc/nginx/gunicorn.conf.py
      - ./backend/local_backup:/app/backup
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8005:8005"
    networks:
      - aws_dealerportal_network
    restart: always

networks:
  aws_dealerportal_network:
    driver: bridge