FROM python:3.11

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH=/app

WORKDIR /app

# Copiar el archivo requirements.txt y luego instalar las dependencias
COPY requirements.txt /app/
RUN pip install --upgrade pip --no-cache-dir \
    && pip install gunicorn --no-cache-dir \
    && pip install -r requirements.txt --no-cache-dir

# Instalar PostgreSQL client
RUN apt-get update && apt-get install -y wget gnupg2 lsb-release \
    && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - \
    && echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list \
    && apt-get update && apt-get install -y postgresql-client-16

# Copiar el código fuente de la aplicación
COPY . /app/

# Ejecutar la actualización de configuración de Celery
# RUN celery upgrade settings /app/dealerportal/settings.py

# Exponer el puerto
EXPOSE 8005

# Comando para iniciar la aplicación Django
CMD sh -c "python manage.py makemigrations && python manage.py migrate && \
           celery -A dealerportal worker --loglevel=info --concurrency=4 & \
           celery -A dealerportal beat --loglevel=info & \
           gunicorn --bind 0.0.0.0:8005 dealerportal.wsgi:application"
