[supervisord]
logfile=/var/log/supervisor/supervisord.log
childlogdir=/var/log/supervisor
nodaemon=true
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

; ==== Programs ====
[program:gunicorn]
directory=/app
command=/usr/local/bin/gunicorn dealerportal.wsgi:application --bind 0.0.0.0:8005 --workers 3 --timeout 120
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true

[program:celery-worker]
directory=/app
command=/usr/local/bin/celery -A dealerportal worker --loglevel=info
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true

[program:celery-beat]
directory=/app
command=/usr/local/bin/celery -A dealerportal beat --loglevel=info
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true
stopasgroup=true
killasgroup=true
