# Generated by Django 4.2 on 2023-06-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile-pic.png",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
