# Generated by Django 4.2 on 2023-06-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_user_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealeraccount",
            name="zoho_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
