# Generated by Django 4.2 on 2023-06-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_dealeraccount_zoho_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealeraccount",
            name="zoho_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
