# Generated by Django 4.2 on 2023-07-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_dealeraccount_zoho_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
