# Generated by Django 4.2 on 2023-07-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_product_image_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=8
            ),
        ),
    ]
