FROM nginx:latest

# # Copia el archivo de configuración de Nginx
# COPY nginx_react_django.conf /etc/nginx/nginx.conf

# # Añade la entrada al archivo /etc/hosts
# RUN echo "10.1.10.216 integration.nws.com" >> /etc/hosts
