# Generated by Django 4.2 on 2023-04-25 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppConfig",
            fields=[
                ("app_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="app_logos/"),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "zoho_client_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "zoho_client_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "zoho_org_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("zoho_refresh_time", models.DurationField(blank=True, null=True)),
                (
                    "zoho_refresh_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "app_admin",
                    models.OneToOneField(
                        limit_choices_to={"role": "AppAdmin"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
