# Generated by Django 4.2 on 2023-04-26 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import zoho_api.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zoho_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='zoho_redirect_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='app_admin',
            field=models.OneToOneField(default=zoho_api.models.get_default_app_admin, limit_choices_to={'role': 'AppAdmin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
