# Generated by Django 4.2 on 2023-05-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoho_api", "0002_appconfig_zoho_redirect_uri_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconfig",
            name="zoho_last_sync_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
