# Generated by Django 4.2 on 2023-05-08 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zoho_api", "0003_appconfig_zoho_last_sync_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="appconfig",
            name="zoho_connection_configured",
            field=models.BooleanField(default=False),
        ),
    ]
